export type DoubleDatePickerProps = {
  ariaLabelPrevious?: string;
  ariaLabelNext?: string;
  open?: boolean;
  onChange?: (startDate: Date | null, endDate?: Date | null) => void;
  labelFrom: string;
  labelTo?: string;
  disableDate?: (date: Date) => boolean;
  disabled?: boolean;
  enableDate?: (date: Date) => boolean;
  id: string;
  selectedStartDate?: Date;
  selectedEndDate?: Date;
  inputValueStart?: string;
  inputValueEnd?: string;
  inputSize?: 's';
  variant: 'DOUBLE';
  width?: number | string;
  ref?: React.Ref<HTMLDivElement>;
  yearSelectLength?: number;
  disallowSingleDayRange?: boolean;
};
