import Color from 'color';
// import accessabilityColors from "./accessabilityColors";
import defaultColors from './defaultColors';
import { RawColors, ThemeColors, ThemeColorsVersion } from './theme.types';

export const getColorDarkScheme = (scheme: ThemeColorsVersion) => {
  switch (scheme) {
    // case 'a11y': return accessabilityColors;
    default:
      return defaultColors;
  }
};

export const createDarkColors = (rawColor: RawColors): ThemeColors => {
  const lineColors = [
    rawColor.complementaryPink1,
    rawColor.complementaryBlue1,
    rawColor.complementaryTurquoise1,
    rawColor.complementaryGreen1,
    rawColor.brandPink,
    rawColor.complementaryGreen2,
    rawColor.complementaryBlue2,
    rawColor.complementaryPink2,
    rawColor.complementaryTurquoise2,
    rawColor.gray1,
  ];

  // prettier-ignore
  return {
    backgroundInput: rawColor.brandPink,
    background: rawColor.brandPink,
    backgroundBlack: rawColor.brandPink,
    backgroundDark: rawColor.brandPink,
    searchBackground: rawColor.brandPink,
    barScaleActiveBar: rawColor.brandPink,
    barScaleInactiveBar: rawColor.brandPink,
    bubbleBackground: rawColor.brandPink,
    bubbleBorder: rawColor.brandPink,
    bubbleSecondaryText: rawColor.brandPink,
    tableBorder: rawColor.brandPink,
    bulbBackground: rawColor.brandPink,
    buttonSecondaryBackground: rawColor.brandPink,
    buttonText: rawColor.brandPink,
    buy: rawColor.brandPink,
    buyActive: rawColor.brandPink,
    borderActive: rawColor.brandPink,
    card: rawColor.brandPink,
    cta: rawColor.brandPink,
    disabledText: rawColor.brandPink,
    disabledBackground: rawColor.brandPink,
    divider: rawColor.brandPink,
    emptyState: rawColor.brandPink,
    fundExchange: rawColor.brandPink,
    label: rawColor.brandPink,
    accordionText: rawColor.brandPink,
    selectOptionBackground: rawColor.brandPink,
    marketingCardMortageHighlight: rawColor.brandPink,
    menuAccent1: rawColor.brandPink,
    menuAccent2: rawColor.brandPink,
    menuAccent3: rawColor.brandPink,
    menuAccent4: rawColor.brandPink,
    menuAccent5: rawColor.brandPink,
    messageCentralFaqIcon: rawColor.brandPink,
    messageCentralFaqButtonBorder: rawColor.brandPink,
    modalBackdrop: Color(rawColor.brandPink).alpha(0.63).rgb().string(),
    module: rawColor.brandPink,
    negative: rawColor.brandPink,
    negativeBlackBackground: rawColor.brandPink,
    otherMonthDateText: rawColor.brandPink,
    positive: rawColor.brandPink,
    sell: rawColor.brandPink,
    sellActive: rawColor.brandPink,
    separator: rawColor.brandPink,
    shadowCard: Color(rawColor.brandPink).alpha(0.03).rgb().string(),
    shadowModal: Color(rawColor.brandPink).alpha(0.16).rgb().string(),
    shadowInput: Color(rawColor.brandPink).alpha(0.03).rgb().string(),
    shadowSwitch: Color(rawColor.brandPink).alpha(0.05).rgb().string(),
    shareville: rawColor.brandPink,
    skeleton: rawColor.brandPink,
    spinnerBlack: rawColor.brandPink,
    spinnerWhite: rawColor.brandPink,
    starRating: rawColor.brandPink,
    starRatingOff: rawColor.brandPink,
    streamingBolt: rawColor.brandPink,
    svgFill: rawColor.brandPink,
    svgStroke: rawColor.brandPink,
    svgStokeLight: rawColor.brandPink,
    text: rawColor.brandPink,
    textLight: rawColor.brandPink, // FIXME: to be removed later
    warning: rawColor.brandPink,
    iconBackdropCta: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    inputBorder: rawColor.brandPink,
    inputBorderHover: rawColor.brandPink,
    tableRowBackground: rawColor.brandPink,
    tableRowHover: rawColor.brandPink,
    datePickerWithinRangeBackground: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    datePickerWithinRangeFade: Color(rawColor.brandPink).alpha(0.01).rgb().string(),
    flagBorder: rawColor.brandPink,
    inputBorderError: rawColor.brandPink,
    inputBorderSuccess: rawColor.brandPink,
    generationSavingsTimelineColor1: rawColor.brandPink,
    generationSavingsTimelineColor2: rawColor.brandPink,
    generationSavingsTimelineColor3: rawColor.brandPink,
    generationSavingsTimelineColor4: rawColor.brandPink,
    guidanceSelectionCardIcon: rawColor.brandPink,
    orderDepthBackground: rawColor.brandPink,
    orderDepthDarkBackground: rawColor.brandPink,
    orderAccountLabel: rawColor.brandPink,
    listItemBackgroundHover: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    loanRatesGraphColor2: rawColor.brandPink,
    selectionCardBorder: rawColor.brandPink,
    selectionCardText: rawColor.brandPink,
    sliderColor: rawColor.brandPink,
    sliderSecondary: rawColor.brandPink,
    sliderDisabled: rawColor.brandPink,
    sliderThumbBackground: rawColor.brandPink,
    sliderBackgroundColor: rawColor.brandPink,
    statusFulfilledBackgroundColor: rawColor.brandPink,
    statusFulfilledTextColor: rawColor.brandPink,
    switchReadOnlyTrackBg: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    switchReadOnlyKnobBg: rawColor.brandPink,
    dateAvatarBackground1: rawColor.brandPink,
    dateAvatarBackground2: rawColor.brandPink,
    dateAvatarText1: rawColor.brandPink,
    dateAvatarText2: rawColor.brandPink,
    transferPendingIconColor: rawColor.brandPink,
    timelineActive: rawColor.brandPink,
    timelineSuccess: rawColor.brandPink,
    timelineWarning: rawColor.brandPink,
    timelineFailure:rawColor.brandPink,
    timelineNext: rawColor.brandPink,
    transferProgressBar1: rawColor.brandPink,
    transferProgressBar2: rawColor.brandPink,
    transferProgressBar3: rawColor.brandPink,
    transferProgressBarText1: rawColor.brandPink,
    transferProgressBarText2: rawColor.brandPink,
    transferStatusBannerBackground1: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    transferStatusBannerBackground2: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    transferStatusBannerBackground3: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    transferStatusBannerText1: rawColor.brandPink,
    transferStatusBannerText2: rawColor.brandPink,
    transferStatusBannerText3: rawColor.brandPink,
    transferStatusBannerChevron: rawColor.brandPink,
    onboardingAccentBlue: rawColor.brandPink,
    onboardingAccentGreen: rawColor.brandPink,
    onboardingAccentPink: rawColor.brandPink,
    onboardingAccentTurquoise: rawColor.brandPink,
    progressBarText: rawColor.brandPink,
    progressBarDone: rawColor.brandPink,
    progressBarActive: rawColor.brandPink,
    progressBarFailure: rawColor.brandPink,
    progressBarWarning: rawColor.brandPink,
    progressBarNext: rawColor.brandPink,
    indexFundsBackground: rawColor.brandPink,
    indexFundsNorwegianAccent: rawColor.brandPink,
    indexFundsFinnishAccent: [
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
    ],
    investmentPredictionGraphPink: rawColor.brandPink,
    investmentPredictionGraphBlue: rawColor.brandPink,
    investmentPredictionGraphGreen: rawColor.brandPink,
    investmentPredictionGraphTurquoise: rawColor.brandPink,
    privateBankingBannerTitle: rawColor.brandPink,
    privateBankingBannerText: rawColor.brandPink,
    privateBankingBannerBackground: rawColor.brandPink,
    paletteMap: [
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
    ],
    palettePink: rawColor.palettes.pink,
    paletteGreen: rawColor.palettes.green,
    paletteBlue: rawColor.palettes.blue,
    paletteTurquoise: rawColor.palettes.turquoise,
    paletteLineGraph: [rawColor.cta, rawColor.index, ...lineColors],
    /** @deprecated  */ creditsPiePrimary: rawColor.complementaryPink1,
    /** @deprecated  */ creditsPieSecondary: rawColor.complementaryPink2,
    /** @deprecated  */ disabled: rawColor.gray3,
    /** @deprecated  */ mapColor1: rawColor.complementaryBlue2,
    /** @deprecated  */ mapColor2: rawColor.complementaryBlue1,
    /** @deprecated  */ mapColor3: rawColor.brandBlue,
    /** @deprecated  */ mapColor4: rawColor.gray1,
    /** @deprecated  */ mapColor5: rawColor.gray3,
    /** @deprecated  */ pieChartColor2: rawColor.brandPink,
  };
};
