import Color from 'color';
// import accessabilityColors from "./accessabilityColors";
import defaultColors from './defaultColors';
import { RawColors, ThemeColors, ThemeColorsVersion } from './theme.types';

export const getColorDarkScheme = (scheme: ThemeColorsVersion) => {
  switch (scheme) {
    // case 'a11y': return accessabilityColors;
    default:
      return defaultColors;
  }
};

export const createDarkColors = (rawColor: RawColors): ThemeColors => {
  const lineColors = [
    rawColor.complementaryPink1,
    rawColor.complementaryBlue1,
    rawColor.complementaryTurquoise1,
    rawColor.complementaryGreen1,
    rawColor.brandPink,
    rawColor.complementaryGreen2,
    rawColor.complementaryBlue2,
    rawColor.complementaryPink2,
    rawColor.complementaryTurquoise2,
    rawColor.gray1,
  ];

  // prettier-ignore
  return {
    backgroundInput: rawColor.white,
    background: rawColor.gray7,
    backgroundBlack: rawColor.black,
    backgroundDark: rawColor.gray0,
    searchBackground: rawColor.gray1,
    barScaleActiveBar: rawColor.complementaryBlue1,
    barScaleInactiveBar: rawColor.gray6,
    bubbleBackground: rawColor.white,
    bubbleBorder: rawColor.gray4,
    bubbleSecondaryText: rawColor.gray2,
    tableBorder: rawColor.gray0,
    bulbBackground: rawColor.brandGreen,
    buttonSecondaryBackground: rawColor.white,
    buttonText: rawColor.white,
    buttonTextLight: rawColor.black,
    buy: rawColor.cta,
    buyActive: rawColor.ctaPressed,
    borderActive: rawColor.cta,
    card: rawColor.white,
    cta: rawColor.cta,
    disabledText: rawColor.gray3,
    disabledBackground: rawColor.gray6,
    divider: rawColor.gray6,
    emptyState: rawColor.gray4,
    fundExchange: rawColor.gray2,
    label: rawColor.gray2,
    accordionText: rawColor.gray2,
    selectOptionBackground: rawColor.white,
    marketingCardMortageHighlight: rawColor.brandTurquoise,
    menuAccent1: rawColor.brandGreen,
    menuAccent2: rawColor.brandTurquoise,
    menuAccent3: rawColor.index,
    menuAccent4: rawColor.brandPink,
    menuAccent5: rawColor.brandPink,
    messageCentralFaqIcon: rawColor.brandPink,
    messageCentralFaqButtonBorder: rawColor.brandPink,
    modalBackdrop: Color(rawColor.brandPink).alpha(0.63).rgb().string(),
    module: rawColor.brandPink,
    negative: rawColor.brandPink,
    negativeBlackBackground: rawColor.brandPink,
    otherMonthDateText: rawColor.brandPink,
    positive: rawColor.brandPink,
    sell: rawColor.brandPink,
    sellActive: rawColor.brandPink,
    separator: rawColor.brandPink,
    shadowCard: Color(rawColor.brandPink).alpha(0.03).rgb().string(),
    shadowModal: Color(rawColor.brandPink).alpha(0.16).rgb().string(),
    shadowInput: Color(rawColor.brandPink).alpha(0.03).rgb().string(),
    shadowSwitch: Color(rawColor.brandPink).alpha(0.05).rgb().string(),
    shareville: rawColor.brandPink,
    skeleton: rawColor.brandPink,
    spinnerBlack: rawColor.brandPink,
    spinnerWhite: rawColor.brandPink,
    starRating: rawColor.brandPink,
    starRatingOff: rawColor.brandPink,
    streamingBolt: rawColor.brandPink,
    svgFill: rawColor.brandPink,
    svgStroke: rawColor.brandPink,
    svgStokeLight: rawColor.brandPink,
    text: rawColor.brandPink,
    textLight: rawColor.brandPink, // FIXME: to be removed later
    warning: rawColor.brandPink,
    iconBackdropCta: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    inputBorder: rawColor.brandPink,
    inputBorderHover: rawColor.brandPink,
    tableRowBackground: rawColor.brandPink,
    tableRowHover: rawColor.brandPink,
    datePickerWithinRangeBackground: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    datePickerWithinRangeFade: Color(rawColor.brandPink).alpha(0.01).rgb().string(),
    flagBorder: rawColor.brandPink,
    inputBorderError: rawColor.brandPink,
    inputBorderSuccess: rawColor.brandPink,
    generationSavingsTimelineColor1: rawColor.brandPink,
    generationSavingsTimelineColor2: rawColor.brandPink,
    generationSavingsTimelineColor3: rawColor.brandPink,
    generationSavingsTimelineColor4: rawColor.brandPink,
    guidanceSelectionCardIcon: rawColor.brandPink,
    orderDepthBackground: rawColor.gray6,
    orderDepthDarkBackground: rawColor.gray5,
    orderAccountLabel: rawColor.gray1,
    listItemBackgroundHover: Color(rawColor.complementaryTurquoise1).alpha(0.1).rgb().string(),
    loanRatesGraphColor2: rawColor.complementaryBlue2,
    selectionCardBorder: rawColor.gray5,
    selectionCardText: rawColor.gray2,
    sliderColor: rawColor.cta,
    sliderSecondary: rawColor.brandGreen,
    sliderDisabled: rawColor.gray6,
    sliderThumbBackground: rawColor.white,
    sliderBackgroundColor: rawColor.gray6,
    statusFulfilledBackgroundColor: rawColor.cta,
    statusFulfilledTextColor: rawColor.white,
    switchReadOnlyTrackBg: Color(rawColor.cta).alpha(0.1).rgb().string(),
    switchReadOnlyKnobBg: rawColor.gray7,
    dateAvatarBackground1: rawColor.gray6,
    dateAvatarBackground2: rawColor.gray7,
    dateAvatarText1: rawColor.gray2,
    dateAvatarText2: rawColor.gray0,
    transferPendingIconColor: rawColor.index,
    timelineActive: rawColor.cta,
    timelineSuccess: rawColor.positive,
    timelineWarning: rawColor.index,
    timelineFailure: rawColor.negative,
    timelineNext: rawColor.gray4,
    transferProgressBar1: rawColor.brandPink,
    transferProgressBar2: rawColor.brandPink,
    transferProgressBar3: rawColor.brandPink,
    transferProgressBarText1: rawColor.brandPink,
    transferProgressBarText2: rawColor.brandPink,
    transferStatusBannerBackground1: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    transferStatusBannerBackground2: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    transferStatusBannerBackground3: Color(rawColor.brandPink).alpha(0.1).rgb().string(),
    transferStatusBannerText1: rawColor.brandPink,
    transferStatusBannerText2: rawColor.brandPink,
    transferStatusBannerText3: rawColor.brandPink,
    transferStatusBannerChevron: rawColor.brandPink,
    onboardingAccentBlue: rawColor.brandPink,
    onboardingAccentGreen: rawColor.brandPink,
    onboardingAccentPink: rawColor.brandPink,
    onboardingAccentTurquoise: rawColor.brandPink,
    progressBarText: rawColor.brandPink,
    progressBarDone: rawColor.brandPink,
    progressBarActive: rawColor.brandPink,
    progressBarFailure: rawColor.brandPink,
    progressBarWarning: rawColor.brandPink,
    progressBarNext: rawColor.brandPink,
    indexFundsBackground: rawColor.brandPink,
    indexFundsNorwegianAccent: rawColor.brandPink,
    indexFundsFinnishAccent: [
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
    ],
    investmentPredictionGraphPink: rawColor.brandPink,
    investmentPredictionGraphBlue: rawColor.brandPink,
    investmentPredictionGraphGreen: rawColor.brandPink,
    investmentPredictionGraphTurquoise: rawColor.brandPink,
    privateBankingBannerTitle: rawColor.brandPink,
    privateBankingBannerText: rawColor.brandPink,
    privateBankingBannerBackground: rawColor.brandPink,
    paletteMap: [
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
      rawColor.brandPink,
    ],
    palettePink: rawColor.palettes.pink,
    paletteGreen: rawColor.palettes.green,
    paletteBlue: rawColor.palettes.blue,
    paletteTurquoise: rawColor.palettes.turquoise,
    paletteLineGraph: [rawColor.cta, rawColor.index, ...lineColors],
    /** @deprecated  */ creditsPiePrimary: rawColor.complementaryPink1,
    /** @deprecated  */ creditsPieSecondary: rawColor.complementaryPink2,
    /** @deprecated  */ disabled: rawColor.gray3,
    /** @deprecated  */ mapColor1: rawColor.complementaryBlue2,
    /** @deprecated  */ mapColor2: rawColor.complementaryBlue1,
    /** @deprecated  */ mapColor3: rawColor.brandBlue,
    /** @deprecated  */ mapColor4: rawColor.gray1,
    /** @deprecated  */ mapColor5: rawColor.gray3,
    /** @deprecated  */ pieChartColor2: rawColor.brandPink,
  };
};
