import ca from './ca';
import de from './de';
import eu from './eu';
import fr from './fr';
import ru from './ru';
import gb from './gb';
import dk from './dk';
import fi from './fi';
import no from './no';
import se from './se';
import us from './us';
import jp from './jp';
import cn from './cn';
import india from './in';
import za from './za';
import hk from './hk';
import br from './br';
import au from './au';

export default { ca, de, eu, fr, ru, gb, dk, fi, no, se, us, jp, cn, in: india, za, hk, br, au };
